apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfastapi-deployment
  labels:
    app: myfastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myfastapi
  template:
    metadata:
      labels:
        app: myfastapi
    spec:
      containers:
      - name: myfastapi
        image: tonyjoanes/myfastapi
        ports:
        - containerPort: 80
